# Tutorial - F-theory compactification

In this tutorial we utilize some of fiber-polytope routines to study F-theory compactifications.

First we import the package.

If installed with pip use the first line if you want to use the .sage file directly, e.g. when using in the cloud use the second line.

In [1]:
#from fiberpolytope import fiberpolytope
load('fiberpolytope.sage')

## K3

Lets take some vertices defining a K3 manifold

In [2]:
vertices = [[0,0,0], [-1,-1,0],[-1,0,0],[0,-1,0],[1,-1,0],[0,0,1],
            [0,1,0],[0,1,1],[1,0,1],[1,1,1],[2,0,1],[1,1,2],[2,1,2],[0,0,-1]]

We feed them into the fiberpolytope

In [3]:
M = fiberpolytope(vertices)

The fiberpolytope contains all functions of the sage polytope class. They are accessed via 

```python
M.polytope.function(). 
```

We can check reflexivity, hodge number, ... . Note, the package will complain, if you give it a non 
reflexive polytope.

In [4]:
# is reflexive?
M.polytope.is_reflexive()

True

What about picard group (hodge numbers, ...) using PALP of the polytope and its mirror?

In [5]:
# hodge numbers
print(M.polytope.poly_x("g"))
# polar hodge numbers
print(M.polytope.polar().poly_x("g"))

M:15 9 N:14 9 Pic:10 Cor:1

M:14 9 N:15 9 Pic:11 Cor:1



Lets have a look at all the points in the polytope. Sage adds all interior vertices even if they haven't been explicitly specified. Furthermore it also changes the order.

In [6]:
M.polytope.points()

M(-1, -1,  0),
M(-1,  0,  0),
M( 2,  1,  2),
M( 0,  0, -1),
M( 2,  0,  1),
M( 1,  1,  2),
M( 0,  1,  0),
M( 0,  1,  1),
M( 1, -1,  0),
M( 1,  0,  0),
M( 1,  1,  1),
M( 1,  0,  1),
M( 0,  0,  0),
M( 0, -1,  0),
M( 0,  0,  1)
in 3-d lattice M

What we are really interested in are fibrations. So lets search for them.

In [7]:
M.find_fibrations()

{'cubic': [(array([ 0,  3, 10]), array([], dtype=float64)),
  (array([0, 6, 9]), array([ 2,  3,  4,  5,  7, 10, 11])),
  (array([ 1,  3, 11]), array([ 0,  2,  5,  6,  7,  8, 10, 13])),
  (array([1, 6, 8]), array([ 2,  3,  4,  5,  7, 10, 11])),
  (array([ 3,  7, 12]), array([ 0,  1,  2,  4,  5,  8,  9, 10, 11]))],
 'P1xP1': [(array([[ 1,  9],
          [ 3, 13]]), array([ 0,  2,  4,  5,  6,  7, 10, 11])),
  (array([[ 1,  9],
          [ 6, 12]]), array([ 0,  2,  4,  5,  7,  8, 10, 11, 13])),
  (array([[ 3, 13],
          [ 1,  9]]), array([ 0,  2,  4,  5,  6,  7, 10, 11])),
  (array([[ 3, 13],
          [ 6, 12]]), array([ 0,  1,  2,  4,  5,  7,  8,  9, 10, 11])),
  (array([[ 6, 12],
          [ 1,  9]]), array([ 0,  2,  4,  5,  7,  8, 10, 11, 13])),
  (array([[ 6, 12],
          [ 3, 13]]), array([ 0,  1,  2,  4,  5,  7,  8,  9, 10, 11]))],
 'P112': [(array([ 0,  5,  3, 13]), array([], dtype=float64)),
  (array([ 0,  8,  6, 12]), array([ 2,  3,  4,  5,  7, 10, 11])),
  (array([3, 4, 1,

How do we have to interpret these results? 

*fiperpolytope* returns a dictionary of possible P112, P1xP1 and cubic fibrations. 
Each entry ('cubic', ..) contains a list of tuples, where the first element denotes the indices of fiber coordinates and the second element the indices of base coordinates under a 'trivial' projection. With trivial projection we mean projection onto the zeros of the fibration coordinates.

There are a few things to note, first base and fibration indices do not necessarily include all variables. Missing variables that project onto the origin are blow ups of the fibration ambient space.

Second, it currently only (reliably) works with trivial projections.

Generally, you can always find some information about any kind of function by using the help function.

In [8]:
help(M.find_fibrations)

Help on method find_fibrations in module __main__:

find_fibrations(symbolic_output=False) method of __main__.fiberpolytope instance
    Finds fibrations and a possible set of suitable base coordinates.
    
    The ambient fibration coordinates are found by studying 
    the defining CY surface and its monomial degrees.
    
    The potential base coordinates are found by looking for all
    rays with non trivial charges in the direction
     with trivial entries for the fiber coordinates.
    
    Parameters
    ----------
    sybolic_output : bool, optional
        If True: return a symbolic dictionary. IMPLEMENT THIS
        
    Returns
    -------
    dict{'cubic': list, 'P1xP1': list, 'P112': list}
        A dictionary with a list of tuples of np.arrays.
        Each tuple consists of 
        (fibration_ambient_coordinates, suitable base spaces)



# CY3 Example

What we are really interested in are compactifications to six or four dimensions. Next, we will look at some simple threefold compactification to six dimensions.

Take the following vertices.

In [9]:
vertices2 = [  [-1, -1, 0, 0], [-1, 0, 0, 0], [0, -1, 0, 0], [1, -1, 0, 0], [0, 1,
   0, 0], [0, 0, 1, 0],  [0, 1, 1, 0], [1, 0, 1, 0], [1, 1, 1, 0], [2,
   0, 1, 0], [1, 1, 2, 0], [2, 1, 2, 0], [-1, 0, -1, -1], [0, 0, 0, 
  1]]

In [10]:
X = fiberpolytope(vertices2)

Check some basic properties of this polytope:

In [11]:
X.polytope.is_reflexive()

True

In [12]:
X.polytope.poly_x("g")

'M:15 10 N:46 16 H:38,12 [52]\n'

Again, we find that sage changes the order internally, when checking for missing rays. We find all the points by

In [13]:
X.polytope.points()

M(-1, -1,  0,  0),
M(-1,  0, -1, -1),
M(-1,  0,  0,  0),
M( 2,  1,  2,  0),
M( 0,  0,  0,  1),
M( 1,  1,  2,  0),
M( 0,  1,  0,  0),
M( 0,  1,  1,  0),
M( 1, -1,  0,  0),
M( 2,  0,  1,  0),
M( 1,  1,  1,  0),
M( 0,  0,  1,  0),
M( 1,  0,  1,  0),
M( 0,  0,  0,  0),
M( 0, -1,  0,  0)
in 4-d lattice M

Or as a numpy array to work with.

In [14]:
X.p_array

array([[-1, -1,  0,  0],
       [-1,  0, -1, -1],
       [-1,  0,  0,  0],
       [ 2,  1,  2,  0],
       [ 0,  0,  0,  1],
       [ 1,  1,  2,  0],
       [ 0,  1,  0,  0],
       [ 0,  1,  1,  0],
       [ 1, -1,  0,  0],
       [ 2,  0,  1,  0],
       [ 1,  1,  1,  0],
       [ 0,  0,  1,  0],
       [ 1,  0,  1,  0],
       [ 0,  0,  0,  0],
       [ 0, -1,  0,  0]])

Lets look for fibrations.

In [15]:
fibrations = X.find_fibrations()
fibrations

{'cubic': [(array([ 1,  4, 12]), array([ 0,  3,  5,  6,  7,  8, 10])),
  (array([2, 6, 8]), array([ 1,  3,  4,  5,  7,  9, 10, 11, 12]))],
 'P1xP1': [],
 'P112': [(array([ 0,  8,  6, 13]),
   array([ 1,  3,  4,  5,  7,  9, 10, 11, 12])),
  (array([ 8,  0,  6, 13]), array([ 1,  3,  4,  5,  7,  9, 10, 11, 12]))]}

We were not able to find any P1xP1 fibrations. However, we are able to bring the polynomial into two different cubic forms and one P112 form. The first cubic form is given by the vertices [1,4,12] and the second by [2,6,8]. 

Let us briefly see, to which vertices these indices belong to; starting with the first found cubic.

In [16]:
fiber, base = fibrations['cubic'][0]
X.polytope.points(fiber)

M(-1, 0, -1, -1),
M( 0, 0,  0,  1),
M( 1, 0,  1,  0)
in 4-d lattice M

while it probably is possible to work with these rays, we note, that the projection would only be trivial on the second coordinate. Thus, lets have a look at the other P2 ambient space.

In [17]:
fiber, base = fibrations['cubic'][1]
X.polytope.points(fiber)

M(-1,  0, 0, 0),
M( 0,  1, 0, 0),
M( 1, -1, 0, 0)
in 4-d lattice M

These vertices can be easily projected onto the last two coordinates, so let us continue with this cubic fibration.

In [18]:
X.polytope.points(base)

M(-1, 0, -1, -1),
M( 2, 1,  2,  0),
M( 0, 0,  0,  1),
M( 1, 1,  2,  0),
M( 0, 1,  1,  0),
M( 2, 0,  1,  0),
M( 1, 1,  1,  0),
M( 0, 0,  1,  0),
M( 1, 0,  1,  0)
in 4-d lattice M

In [19]:
X.vertices_to_variables()

[(x1, array([-1, -1,  0,  0])),
 (x2, array([-1,  0, -1, -1])),
 (x3, array([-1,  0,  0,  0])),
 (x4, array([2, 1, 2, 0])),
 (x5, array([0, 0, 0, 1])),
 (x6, array([1, 1, 2, 0])),
 (x7, array([0, 1, 0, 0])),
 (x8, array([0, 1, 1, 0])),
 (x9, array([ 1, -1,  0,  0])),
 (x10, array([2, 0, 1, 0])),
 (x11, array([1, 1, 1, 0])),
 (x12, array([0, 0, 1, 0])),
 (x13, array([1, 0, 1, 0])),
 (x14, array([ 0, -1,  0,  0]))]

If we want to continue working with this fibration, we need to tell the fiberpolytope class.

In [20]:
X.set_fibration(fiber, base, 'cubic')
#X.set_fibration(fiber, base, 'cubic', label=False)

fiberpolytope:WARNING:There might be some warnings about division by zero, do not mind them. All is fine.
/home/robin/Desktop/SageMath/local/lib/python3.7/site-packages/sage/repl/ipython_kernel/__main__.py:338: RuntimeWarning: invalid value encountered in subtract
/home/robin/Desktop/SageMath/local/lib/python3.7/site-packages/sage/repl/ipython_kernel/__main__.py:324: RuntimeWarning: invalid value encountered in true_divide


We note, that there are some warning. Don't worry about them, there is some division by zero in the background when relabeling the base variables. If you don't want the variables to be relabeled use the second line.

Now that we have done that, we can check the new variable names with

In [21]:
X.vertices_to_variables()

[(e1, array([-1, -1,  0,  0])),
 (A10, array([-1,  0, -1, -1])),
 (u, array([-1,  0,  0,  0])),
 (C20, array([2, 1, 2, 0])),
 (B10, array([0, 0, 0, 1])),
 (C21, array([1, 1, 2, 0])),
 (v, array([0, 1, 0, 0])),
 (C10, array([0, 1, 1, 0])),
 (w, array([ 1, -1,  0,  0])),
 (C11, array([2, 0, 1, 0])),
 (C12, array([1, 1, 1, 0])),
 (C13, array([0, 0, 1, 0])),
 (C14, array([1, 0, 1, 0])),
 (e2, array([ 0, -1,  0,  0]))]

or alternatively

In [22]:
X.variables

[e1, A10, u, C20, B10, C21, v, C10, w, C11, C12, C13, C14, e2]

A few notes on the labeling of the coordinates can be found with help(X.label_base).
1. We use capital letters to denote base variables. Each capital letter denotes some ray in the 2d base. The first index, denotes the multiplicity and the second counts how many rays we have of this type. 

Consider our current example: 
1. Take, C10, which projects onto (1,0) under the trivial projection onto the last two coordinates. Since (1,0) is a unit vector it has multiplicity 1, thus C1. Further, it is the first vertex of its type and thus gets count 0, C10.

2. C20, projects onto (2,0) and thus comes with multiplicity 2.

The general cubic/surface equation in terms of polynomial coefficients s_i can be found via (Warning: only implemented for P2 fibrations)

In [23]:
X.wsfmodel()

e1^4*e2^2*s1*u^3 + e1^3*e2^2*s5*u^2*w + e1^2*e2^2*s8*u*w^2 + e1^2*e2*s2*u^2*v + e1*e2^2*s10*w^3 + e1*e2*s6*u*v*w + e2*s9*v*w^2 + s3*u*v^2

Note, the additional e_i coordinates which are blow ups of the fiber ambient P2. Comparing with [1408.4808](https://arxiv.org/abs/1408.4808) we note that we are actually working with an F6 ambient space.

If we want to do some more serious computations, such as studying factorizations and looking at codimension two singularities and higher stuff, we will utilize singular. In order to use singular, we have to set a singular ring first:

In [24]:
X.set_singular_ring('c')

polynomial ring, over a field, global ordering
// coefficients: QQ(c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45)
// number of vars : 14
//        block   1 : ordering dp
//                  : names    e1 A10 u C20 B10 C21 v C10 w C11 C12 C13 C14 e2
//        block   2 : ordering C

In [25]:
s = X.find_s()
s

[(c9)*e1^4*C20^4*C21^6*C10^4*C11*C12^2*C13^5*C14^3*e2^2+(c12)*e1^4*A10*C20^2*C21^4*C10^3*C12*C13^4*C14^2*e2^2+(c13)*e1^4*C20^2*B10*C21^4*C10^3*C12*C13^4*C14^2*e2^2,
 (c28)*e1^2*C20^5*C21^6*C10^4*C11^2*C12^3*C13^4*C14^3*e2+(c29)*e1^2*A10*C20^3*C21^4*C10^3*C11*C12^2*C13^3*C14^2*e2+(c35)*e1^2*C20^3*B10*C21^4*C10^3*C11*C12^2*C13^3*C14^2*e2+(c30)*e1^2*A10^2*C20*C21^2*C10^2*C12*C13^2*C14*e2+(c36)*e1^2*A10*C20*B10*C21^2*C10^2*C12*C13^2*C14*e2+(c38)*e1^2*C20*B10^2*C21^2*C10^2*C12*C13^2*C14*e2,
 (c11)*C20^6*C21^6*C10^4*C11^3*C12^4*C13^3*C14^3+(c39)*A10*C20^4*C21^4*C10^3*C11^2*C12^3*C13^2*C14^2+(c41)*C20^4*B10*C21^4*C10^3*C11^2*C12^3*C13^2*C14^2+(c40)*A10^2*C20^2*C21^2*C10^2*C11*C12^2*C13*C14+(c42)*A10*C20^2*B10*C21^2*C10^2*C11*C12^2*C13*C14+(c44)*C20^2*B10^2*C21^2*C10^2*C11*C12^2*C13*C14+(c0)*A10^3*C10*C12+(c43)*A10^2*B10*C10*C12+(c45)*A10*B10^2*C10*C12+(c1)*B10^3*C10*C12,
 0,
 (c18)*e1^3*C20^4*C21^5*C10^3*C11^2*C12^2*C13^4*C14^3*e2^2+(c19)*e1^3*A10*C20^2*C21^3*C10^2*C11*C12*C13^3*C14^2*e2^2+(c

The function set_singular_ring() takes a parameter, by default 'd' which specifies with which coefficients and variables we want to work with. 'd' here means factorizations of the coefficients s_i into d_i. 

Other options are:

    's' to work with s_i coefficients (boring). 
    
    'c' to work with c_i complex moduli (will kill your memory when computing Delta).

In [26]:
help(X.set_singular_ring)

Help on method set_singular_ring in module __main__:

set_singular_ring(coeff='d') method of __main__.fiberpolytope instance
    Specifies the singular ring.
    This function needs to be called BEFORE doing any 
    symbolic calculations and AFTER specifying the active
    fibration.
    
    Use coeff to specify the variables and coefficients you want 
    to work with.
    
    Options
    -------
    's': s_i coefficients
    'd': refined (factorized) d_i coefficients
    'dv': d coefficients are promoted to variables
    'all': s_i, d_i are promoted to variables and c_i coeff
    'c': c_i coefficients
        Working with cmoduli is very Memory constraint and not recommended.
    
    Parameters
    ----------
    coeff : str , optional
        Pick 's', 'd', 'dv', 'all' or 'c', default = 'c'.
    
    Returns
    -------
    singular_exprs
        singular ring with nMonomial coefficients in
        nVariables char=0 and default dp sorting.



In [27]:
X.set_singular_ring('d')

polynomial ring, over a field, global ordering
// coefficients: QQ(d1, d2, d3, d4, d5, d6, d7, d8, d9, d10)
// number of vars : 14
//        block   1 : ordering dp
//                  : names    e1 A10 u C20 B10 C21 v C10 w C11 C12 C13 C14 e2
//        block   2 : ordering C

We have a look at these factorizations by finding all the d_i's.

In [28]:
d = X.find_d()
d

[(d1)*e1^4*C20^2*C21^4*C10^3*C12*C13^4*C14^2*e2^2,
 (d2)*e1^2*C20*C21^2*C10^2*C12*C13^2*C14*e2,
 (d3)*C10*C12,
 0,
 (d5)*e1^3*C21*C10*C13^2*C14*e2^2,
 (d6)*e1*C20*C21*C10*C11*C12*C13*C14*e2,
 0,
 (d8)*e1^2*C11*C13*C14*e2^2,
 (d9)*C20*C11^2*C12*C14*e2,
 (d10)*e1*C20^2*C21*C11^3*C12*C13*C14^2*e2^2]

Again, we reproduce the vanishing of some of the coefficients and their factorizations.

However, what we are really interested in are f, g and Delta. In order to find f, g and Delta, we call 

```python
M.find_f(coeff)
```

where coeff are the d_i (s_i) coefficients in the general cubic polynomial.

In [29]:
f = X.find_f(d)
f.factorize()

[1]:
   _[1]=-1/48
   _[2]=e1
   _[3]=C10
   _[4]=C11
   _[5]=C12
   _[6]=C13
   _[7]=(-48*d1*d3*d9^2+16*d2^2*d9^2+24*d2*d3*d6*d10-8*d2*d6^2*d9+d6^4)*C20^4*C21^4*C10^2*C11^2*C12^2*C13^2*C14^2+(-16*d2*d3*d8*d9-48*d3^2*d5*d10+24*d3*d5*d6*d9-8*d3*d6^2*d8)*C20^2*C21^2*C10*C11*C12*C13*C14+(16*d3^2*d8^2)
   _[8]=C14
   _[9]=e2
[2]:
   1,4,2,2,2,2,1,2,4

We find that f factorizes into many parts. 

1. The e_i coordinates come with a power of 4, however, since those are just blow ups in the fiber ambient space, we can safely ignore them. 
2. We can blow them down by setting them to 1 (more to that later).
3. The base variables of type C1i appear with a power of 2. In fact the C1i are part of our SO(10).

What about g?

In [30]:
g = X.find_g(d)
g.factorize()

[1]:
   _[1]=-1/864
   _[2]=e1
   _[3]=C10
   _[4]=C11
   _[5]=C12
   _[6]=C13
   _[7]=(-288*d1*d2*d3*d9^3+864*d1*d3^3*d10^2-864*d1*d3^2*d6*d9*d10+72*d1*d3*d6^2*d9^2+64*d2^3*d9^3-216*d2^2*d3^2*d10^2+144*d2^2*d3*d6*d9*d10-48*d2^2*d6^2*d9^2-36*d2*d3*d6^3*d10+12*d2*d6^4*d9-d6^6)*C20^6*C21^6*C10^3*C11^3*C12^3*C13^3*C14^3+(576*d1*d3^2*d8*d9^2-96*d2^2*d3*d8*d9^2+144*d2*d3^2*d5*d9*d10+144*d2*d3^2*d6*d8*d10+144*d2*d3*d5*d6*d9^2-24*d2*d3*d6^2*d8*d9+72*d3^2*d5*d6^2*d10-36*d3*d5*d6^3*d9+12*d3*d6^4*d8)*C20^4*C21^4*C10^2*C11^2*C12^2*C13^2*C14^2+(-96*d2*d3^2*d8^2*d9-288*d3^3*d5*d8*d10-216*d3^2*d5^2*d9^2+144*d3^2*d5*d6*d8*d9-48*d3^2*d6^2*d8^2)*C20^2*C21^2*C10*C11*C12*C13*C14+(64*d3^3*d8^3)
   _[8]=C14
   _[9]=e2
[2]:
   1,6,3,3,3,3,1,3,6

Similarly we find for g a factorization in to ei and C1i with powers of 6 and 3. 


Next, we want to find the discriminant. Here, we can either give the function f and g from our previous results, or it uses the interally saved old results.

In [31]:
Delta = X.find_discriminant()
Delta.factorize()

[1]:
   _[1]=(d3^2)/16
   _[2]=e1
   _[3]=C20
   _[4]=C21
   _[5]=C10
   _[6]=C11
   _[7]=C12
   _[8]=C13
   _[9]=(64*d1^3*d3*d9^6-16*d1^2*d2^2*d9^6-288*d1^2*d2*d3^2*d9^3*d10^2+192*d1^2*d2*d3*d6*d9^4*d10+8*d1^2*d2*d6^2*d9^5+432*d1^2*d3^4*d10^4-864*d1^2*d3^3*d6*d9*d10^3+504*d1^2*d3^2*d6^2*d9^2*d10^2-72*d1^2*d3*d6^3*d9^3*d10-d1^2*d6^4*d9^4+136*d1*d2^3*d3*d9^3*d10^2-48*d1*d2^3*d6*d9^4*d10-216*d1*d2^2*d3^3*d10^4+360*d1*d2^2*d3^2*d6*d9*d10^3-162*d1*d2^2*d3*d6^2*d9^2*d10^2+40*d1*d2^2*d6^3*d9^3*d10-36*d1*d2*d3^2*d6^3*d10^3+48*d1*d2*d3*d6^4*d9*d10^2-11*d1*d2*d6^5*d9^2*d10-d1*d3*d6^6*d10^2+d1*d6^7*d9*d10-16*d2^5*d9^3*d10^2+27*d2^4*d3^2*d10^4-36*d2^4*d3*d6*d9*d10^3+8*d2^4*d6^2*d9^2*d10^2+d2^3*d3*d6^3*d10^3-d2^3*d6^4*d9*d10^2)*C20^10*C21^10*C10^5*C11^5*C12^5*C13^5*C14^5+(-128*d1^2*d2*d3*d8*d9^5+576*d1^2*d3^3*d8*d9^2*d10^2+192*d1^2*d3^2*d5*d9^4*d10-576*d1^2*d3^2*d6*d8*d9^3*d10-96*d1^2*d3*d5*d6*d9^5+80*d1^2*d3*d6^2*d8*d9^4+32*d1*d2^3*d8*d9^5-240*d1*d2^2*d3^2*d8*d9^2*d10^2-176*d1*d2^2*d3*d5*d9^4*d10

1. We find for Delta a factorization in ei and C1i with powers of 12 and 7 respectively. 
2. Furthermore it also comes with power 2 of the C2i coordinates.

Summarizing we found that the C1i come with power (2,3,7) which gives us a SO(10).

3. Finally, delta also factorizes into the coefficient d3^2, see the first entry. 

Next, we want to find out what happens when d3 -> C10. We will use Singular for this. We define a polynomial in singular called 'Delta' which corresponds to the Delta we found before (with Delta.string()).

In [32]:
singular.clear('Delta_singular')
singular.set('poly', 'Delta_singular', Delta.string())

Then, we evaluate into Delta2, what happens when we substitute C10 into d3 in our polynomial description

In [33]:
Delta2 = singular.new(singular.eval('subst(Delta_singular, d3, C10)'))
Delta2.factorize()

[1]:
   _[1]=1/16
   _[2]=e1
   _[3]=C20
   _[4]=C21
   _[5]=C10
   _[6]=C11
   _[7]=C12
   _[8]=C13
   _[9]=(432*d1^2*d10^4)*C20^10*C21^10*C10^6*C11^5*C12^5*C13^5*C14^5+(-864*d1^2*d6*d9*d10^3-216*d1*d2^2*d10^4)*C20^10*C21^10*C10^5*C11^5*C12^5*C13^5*C14^5+(-288*d1^2*d2*d9^3*d10^2+504*d1^2*d6^2*d9^2*d10^2+360*d1*d2^2*d6*d9*d10^3-36*d1*d2*d6^3*d10^3+27*d2^4*d10^4)*C20^10*C21^10*C10^4*C11^5*C12^5*C13^5*C14^5+(64*d1^3*d9^6+192*d1^2*d2*d6*d9^4*d10-72*d1^2*d6^3*d9^3*d10+136*d1*d2^3*d9^3*d10^2-162*d1*d2^2*d6^2*d9^2*d10^2+48*d1*d2*d6^4*d9*d10^2-d1*d6^6*d10^2-36*d2^4*d6*d9*d10^3+d2^3*d6^3*d10^3)*C20^10*C21^10*C10^3*C11^5*C12^5*C13^5*C14^5+(-16*d1^2*d2^2*d9^6+8*d1^2*d2*d6^2*d9^5-d1^2*d6^4*d9^4-48*d1*d2^3*d6*d9^4*d10+40*d1*d2^2*d6^3*d9^3*d10-11*d1*d2*d6^5*d9^2*d10+d1*d6^7*d9*d10-16*d2^5*d9^3*d10^2+8*d2^4*d6^2*d9^2*d10^2-d2^3*d6^4*d9*d10^2)*C20^10*C21^10*C10^2*C11^5*C12^5*C13^5*C14^5+(576*d1^2*d8*d9^2*d10^2+144*d1*d2*d5*d9*d10^3+144*d1*d2*d6*d8*d10^3+72*d1*d5*d6^2*d10^3)*C20^8*C21^8*C10^4*C11^4*C1

We now find that Delta factorizes into C10^12. The whole thing can also be made visually more appealing by blowing down some variables, e.g.

In [34]:
Delta3 = singular.new(singular.eval('subst(Delta_singular, d3, C10, e1, 1, e2, 1, C11, 1, C12, 1, C13, 1, C14, 1)'))
#print(Delta2)
Delta3.factorize()

[1]:
   _[1]=1/16
   _[2]=C20
   _[3]=C21
   _[4]=(432*d1^2*d10^4)*C20^10*C21^10*C10^6+(-864*d1^2*d6*d9*d10^3-216*d1*d2^2*d10^4)*C20^10*C21^10*C10^5+(-288*d1^2*d2*d9^3*d10^2+504*d1^2*d6^2*d9^2*d10^2+360*d1*d2^2*d6*d9*d10^3-36*d1*d2*d6^3*d10^3+27*d2^4*d10^4)*C20^10*C21^10*C10^4+(64*d1^3*d9^6+192*d1^2*d2*d6*d9^4*d10-72*d1^2*d6^3*d9^3*d10+136*d1*d2^3*d9^3*d10^2-162*d1*d2^2*d6^2*d9^2*d10^2+48*d1*d2*d6^4*d9*d10^2-d1*d6^6*d10^2-36*d2^4*d6*d9*d10^3+d2^3*d6^3*d10^3)*C20^10*C21^10*C10^3+(-16*d1^2*d2^2*d9^6+8*d1^2*d2*d6^2*d9^5-d1^2*d6^4*d9^4-48*d1*d2^3*d6*d9^4*d10+40*d1*d2^2*d6^3*d9^3*d10-11*d1*d2*d6^5*d9^2*d10+d1*d6^7*d9*d10-16*d2^5*d9^3*d10^2+8*d2^4*d6^2*d9^2*d10^2-d2^3*d6^4*d9*d10^2)*C20^10*C21^10*C10^2+(576*d1^2*d8*d9^2*d10^2+144*d1*d2*d5*d9*d10^3+144*d1*d2*d6*d8*d10^3+72*d1*d5*d6^2*d10^3)*C20^8*C21^8*C10^4+(192*d1^2*d5*d9^4*d10-576*d1^2*d6*d8*d9^3*d10-240*d1*d2^2*d8*d9^2*d10^2-192*d1*d2*d5*d6*d9^2*d10^2-168*d1*d2*d6^2*d8*d9*d10^2-108*d1*d5*d6^3*d9*d10^2+12*d1*d6^4*d8*d10^2-36*d2^3*d5*d9*d10

### PLaying with more symbolic manipulations

In general, we will have to play around a lot with the sage singular interface. A useful reference for singular sage can be found here:
https://doc.sagemath.org/html/en/reference/interfaces/sage/interfaces/singular.html

Previously we have manually blown down all blow ups in the fiber and all variables that project onto the same C10 ray in the base.

We can do the same thing earlier, by using the following function:

In [35]:
X.blow_down_coordinates()

[1, A10, u, C20, B10, 1, v, C10, w, 1, 1, 1, 1, 1]

In [36]:
help(X.blow_down_coordinates)

Help on method blow_down_coordinates in module __main__:

blow_down_coordinates(fibration=True, base=True, higher=False) method of __main__.fiberpolytope instance
    Blows down coordinates specified by the Boolean arguments.
    The blown down coordinates are internally set to 1.
    
    Parameters
    ----------
    fibration : bool, optional
        fibration blow ups, by default True
    base : bool, optional
        blow ups of the base rays, by default True
    higher : bool, optional
        blow ups of the higher multiplicity base rays, by default False
    
    Returns
    -------
    list
        list of new variables



In [37]:
X.vertices_to_variables()

[(1, array([-1, -1,  0,  0])),
 (A10, array([-1,  0, -1, -1])),
 (u, array([-1,  0,  0,  0])),
 (C20, array([2, 1, 2, 0])),
 (B10, array([0, 0, 0, 1])),
 (1, array([1, 1, 2, 0])),
 (v, array([0, 1, 0, 0])),
 (C10, array([0, 1, 1, 0])),
 (w, array([ 1, -1,  0,  0])),
 (1, array([2, 0, 1, 0])),
 (1, array([1, 1, 1, 0])),
 (1, array([0, 0, 1, 0])),
 (1, array([1, 0, 1, 0])),
 (1, array([ 0, -1,  0,  0]))]

It will internally set all previously mentioned variables to zero. Note though, if we want to continue doing calculations, we have to change our singular ring again. We again want to work on the level of 'd' coefficients.

In [38]:
X.set_singular_ring('d')

polynomial ring, over a field, global ordering
// coefficients: QQ(d1, d2, d3, d4, d5, d6, d7, d8, d9, d10)
// number of vars : 7
//        block   1 : ordering dp
//                  : names    A10 u C20 B10 v C10 w
//        block   2 : ordering C

We can also double check, the current singular ring via

In [39]:
singular.current_ring()

polynomial ring, over a field, global ordering
// coefficients: QQ(d1, d2, d3, d4, d5, d6, d7, d8, d9, d10)
// number of vars : 7
//        block   1 : ordering dp
//                  : names    A10 u C20 B10 v C10 w
//        block   2 : ordering C

finding again our d's

In [40]:
d = X.find_d()
d

[(d1)*C20^2*C10^3,
 (d2)*C20*C10^2,
 (d3)*C10,
 0,
 (d5)*C10,
 (d6)*C20*C10,
 0,
 (d8),
 (d9)*C20,
 (d10)*C20^2]

In [41]:
f = X.find_f(d)
#print(f)
f.factorize()

[1]:
   _[1]=-1/48
   _[2]=(-48*d1*d3*d9^2+16*d2^2*d9^2+24*d2*d3*d6*d10-8*d2*d6^2*d9+d6^4)*C20^4*C10^2+(-16*d2*d3*d8*d9-48*d3^2*d5*d10+24*d3*d5*d6*d9-8*d3*d6^2*d8)*C20^2*C10+(16*d3^2*d8^2)
   _[3]=C10
[2]:
   1,1,2

In [42]:
g = X.find_g(d)
g.factorize()

[1]:
   _[1]=-1/864
   _[2]=(-288*d1*d2*d3*d9^3+864*d1*d3^3*d10^2-864*d1*d3^2*d6*d9*d10+72*d1*d3*d6^2*d9^2+64*d2^3*d9^3-216*d2^2*d3^2*d10^2+144*d2^2*d3*d6*d9*d10-48*d2^2*d6^2*d9^2-36*d2*d3*d6^3*d10+12*d2*d6^4*d9-d6^6)*C20^6*C10^3+(576*d1*d3^2*d8*d9^2-96*d2^2*d3*d8*d9^2+144*d2*d3^2*d5*d9*d10+144*d2*d3^2*d6*d8*d10+144*d2*d3*d5*d6*d9^2-24*d2*d3*d6^2*d8*d9+72*d3^2*d5*d6^2*d10-36*d3*d5*d6^3*d9+12*d3*d6^4*d8)*C20^4*C10^2+(-96*d2*d3^2*d8^2*d9-288*d3^3*d5*d8*d10-216*d3^2*d5^2*d9^2+144*d3^2*d5*d6*d8*d9-48*d3^2*d6^2*d8^2)*C20^2*C10+(64*d3^3*d8^3)
   _[3]=C10
[2]:
   1,1,3

In [43]:
Delta = X.find_discriminant()
Delta.factorize()

[1]:
   _[1]=(d3^2)/16
   _[2]=C20
   _[3]=(64*d1^3*d3*d9^6-16*d1^2*d2^2*d9^6-288*d1^2*d2*d3^2*d9^3*d10^2+192*d1^2*d2*d3*d6*d9^4*d10+8*d1^2*d2*d6^2*d9^5+432*d1^2*d3^4*d10^4-864*d1^2*d3^3*d6*d9*d10^3+504*d1^2*d3^2*d6^2*d9^2*d10^2-72*d1^2*d3*d6^3*d9^3*d10-d1^2*d6^4*d9^4+136*d1*d2^3*d3*d9^3*d10^2-48*d1*d2^3*d6*d9^4*d10-216*d1*d2^2*d3^3*d10^4+360*d1*d2^2*d3^2*d6*d9*d10^3-162*d1*d2^2*d3*d6^2*d9^2*d10^2+40*d1*d2^2*d6^3*d9^3*d10-36*d1*d2*d3^2*d6^3*d10^3+48*d1*d2*d3*d6^4*d9*d10^2-11*d1*d2*d6^5*d9^2*d10-d1*d3*d6^6*d10^2+d1*d6^7*d9*d10-16*d2^5*d9^3*d10^2+27*d2^4*d3^2*d10^4-36*d2^4*d3*d6*d9*d10^3+8*d2^4*d6^2*d9^2*d10^2+d2^3*d3*d6^3*d10^3-d2^3*d6^4*d9*d10^2)*C20^10*C10^5+(-128*d1^2*d2*d3*d8*d9^5+576*d1^2*d3^3*d8*d9^2*d10^2+192*d1^2*d3^2*d5*d9^4*d10-576*d1^2*d3^2*d6*d8*d9^3*d10-96*d1^2*d3*d5*d6*d9^5+80*d1^2*d3*d6^2*d8*d9^4+32*d1*d2^3*d8*d9^5-240*d1*d2^2*d3^2*d8*d9^2*d10^2-176*d1*d2^2*d3*d5*d9^4*d10+80*d1*d2^2*d3*d6*d8*d9^3*d10+16*d1*d2^2*d5*d6*d9^5-32*d1*d2^2*d6^2*d8*d9^4+144*d1*d2*d3^3*d5*d9*d10^3

In [44]:
singular.clear('Delta_singular')
singular.set('poly', 'Delta_singular', Delta.string())
#singular.get('Delta')

In [45]:
Delta2 = singular.new(singular.eval('subst(Delta_singular, d3, C10)'))
#print(Delta2)
Delta2.factorize()

[1]:
   _[1]=1/16
   _[2]=C20
   _[3]=(432*d1^2*d10^4)*C20^10*C10^6+(-864*d1^2*d6*d9*d10^3-216*d1*d2^2*d10^4)*C20^10*C10^5+(-288*d1^2*d2*d9^3*d10^2+504*d1^2*d6^2*d9^2*d10^2+360*d1*d2^2*d6*d9*d10^3-36*d1*d2*d6^3*d10^3+27*d2^4*d10^4)*C20^10*C10^4+(64*d1^3*d9^6+192*d1^2*d2*d6*d9^4*d10-72*d1^2*d6^3*d9^3*d10+136*d1*d2^3*d9^3*d10^2-162*d1*d2^2*d6^2*d9^2*d10^2+48*d1*d2*d6^4*d9*d10^2-d1*d6^6*d10^2-36*d2^4*d6*d9*d10^3+d2^3*d6^3*d10^3)*C20^10*C10^3+(-16*d1^2*d2^2*d9^6+8*d1^2*d2*d6^2*d9^5-d1^2*d6^4*d9^4-48*d1*d2^3*d6*d9^4*d10+40*d1*d2^2*d6^3*d9^3*d10-11*d1*d2*d6^5*d9^2*d10+d1*d6^7*d9*d10-16*d2^5*d9^3*d10^2+8*d2^4*d6^2*d9^2*d10^2-d2^3*d6^4*d9*d10^2)*C20^10*C10^2+(576*d1^2*d8*d9^2*d10^2+144*d1*d2*d5*d9*d10^3+144*d1*d2*d6*d8*d10^3+72*d1*d5*d6^2*d10^3)*C20^8*C10^4+(192*d1^2*d5*d9^4*d10-576*d1^2*d6*d8*d9^3*d10-240*d1*d2^2*d8*d9^2*d10^2-192*d1*d2*d5*d6*d9^2*d10^2-168*d1*d2*d6^2*d8*d9*d10^2-108*d1*d5*d6^3*d9*d10^2+12*d1*d6^4*d8*d10^2-36*d2^3*d5*d9*d10^3-36*d2^3*d6*d8*d10^3+30*d2^2*d5*d6^2*d10^3)*C20^8*C

In [46]:
singular.clear('f')
singular.set('poly', 'f', f.string())
f2 = singular.new(singular.eval('subst(f, d3, C10)'))
#print(Delta2)
f2.factorize()

[1]:
   _[1]=-1/48
   _[2]=(-48*d1*d9^2+24*d2*d6*d10)*C20^4*C10+(16*d2^2*d9^2-8*d2*d6^2*d9+d6^4)*C20^4+(-48*d5*d10)*C20^2*C10+(-16*d2*d8*d9+24*d5*d6*d9-8*d6^2*d8)*C20^2+(16*d8^2)
   _[3]=C10
[2]:
   1,1,4

In [47]:
singular.clear('g')
singular.set('poly', 'g', g.string())
g2 = singular.new(singular.eval('subst(g, d3, C10)'))
#print(Delta2)
g2.factorize()

[1]:
   _[1]=-1/864
   _[2]=(864*d1*d10^2)*C20^6*C10^3+(-864*d1*d6*d9*d10-216*d2^2*d10^2)*C20^6*C10^2+(-288*d1*d2*d9^3+72*d1*d6^2*d9^2+144*d2^2*d6*d9*d10-36*d2*d6^3*d10)*C20^6*C10+(64*d2^3*d9^3-48*d2^2*d6^2*d9^2+12*d2*d6^4*d9-d6^6)*C20^6+(576*d1*d8*d9^2+144*d2*d5*d9*d10+144*d2*d6*d8*d10+72*d5*d6^2*d10)*C20^4*C10+(-96*d2^2*d8*d9^2+144*d2*d5*d6*d9^2-24*d2*d6^2*d8*d9-36*d5*d6^3*d9+12*d6^4*d8)*C20^4+(-288*d5*d8*d10)*C20^2*C10+(-96*d2*d8^2*d9-216*d5^2*d9^2+144*d5*d6*d8*d9-48*d6^2*d8^2)*C20^2+(64*d8^3)
   _[3]=C10
[2]:
   1,1,6

Thus we find that at codim2 when d3 -> C10 we have a (4,6,12) singularity.

### Resetting information

In order to reset our fibration to the initially used one without any blown downs we sort again.

In [48]:
X._sort_variables()

In [49]:
X.variables

[e1, A10, u, C20, B10, C21, v, C10, w, C11, C12, C13, C14, e2]

Note, that, if we want to do more symbolic computations, we'd have to reconfigure the singular ring.

In [50]:
help(X.clear_fibration)

Help on method clear_fibration in module __main__:

clear_fibration() method of __main__.fiberpolytope instance
    Resets all active calculation to the base Polytope



That's it. There is another tutorial which deals more with the fibration structure of the reflexive polytopes.